blank_issues_enabled: false
contact_links:
  - name: Discussions on GitHub ðŸ’¬
    url: https://github.com/ChristopherGabba/react-native-nitro-screen-recorder/discussions
    about: If this library works as promised but you need help, please ask questions there.
